---
title: "PLAGIARISM_DETECTION"
author: "GMD"
date: "4/6/2021"
output: 
  slidy_presentation:
    df_print: paged
---

```{r setup, include=FALSE, echo=FALSE}
library(reticulate)
```

## Import library
```{python}
import pandas as pd
import re
import os
import glob
import operator
import math
```

## Text Cleaner
```{python}
def cleaner(text):
    #remove newline
    text = text.replace('\n', ' ')
    #remove multiple spaces
    text = re.sub(' +', ' ', text)
    #remove special characters and numbers
    text = re.sub('[^A-Za-z\- ]', '', text)
    
    return text.lower()
```

## Import dataset
```{python}
documents = list()
#Import all .txt file in dataset folder
for filename in glob.glob(os.path.join('../dataset/', '*.txt')):
   with open(os.path.join(os.getcwd(), filename), 'r', encoding='mbcs') as f: # open in readonly mode
      documents.append(cleaner(f.read()))
```

## Kamus Indonesia
```{python}
bahasa = open('../models/Indonesia.txt', 'r')
bahasa = bahasa.read().split('\n')
```
```{r echo=FALSE}
data.frame(py$bahasa)
```

## Hitung semua kata yang muncul
```{python}
def computeAllWords(docs):
    all_words = set()
    for text in docs:
        for word in text.split():
            if word in bahasa:
                all_words.add(word)    
    return all_words

allWords = computeAllWords(documents)
allWords = list(allWords)
```
```{r echo=FALSE}
data.frame(py$allWords)
```

## Hitung IDF
```{python}
def computeIDF(allWords):
    N = len(documents)
    words_idf = dict()
    for word in allWords:
        words_idf[word] = 0

    for word in allWords:
        #Hitung nx
        nx = 0
        for doc in documents:
            if word in doc:
                nx += 1
        words_idf[word] = math.log((N + 1)/nx, 2)

    return words_idf

allWords = computeIDF(allWords)
words_idf = pd.DataFrame(list(allWords.items()),columns = ['word','idf']) 
```
```{r echo=FALSE}
data.frame(py$words_idf)
```

## Buat Data Frame
```{python}
df = pd.DataFrame()
doc = ['DOC {}'.format(i) for i in range(30)]
df['doc'] = doc
zeros = [0] * 30
for i in allWords.keys():
    df[i] = zeros
```
```{r echo=FALSE}
py$df
```

## Hitung dan isi TF-IDF
```{python}
for i in range(len(df.index)):
  for word in allWords.keys():
    print((documents[i].count(word)/len(documents[i].split())))
```
```{r echo=FALSE}
py$df
```












